# Generated by Django 4.0.4 on 2022-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_city_latitude_alter_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
