# Generated by Django 4.0.4 on 2022-06-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_appuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Application User', 'verbose_name_plural': 'Application Users'},
        ),
    ]
